### ISSUE TITLE
Does GherkinSpec work with .NET 4.6 ?

### ISSUE THREAD

**Issue by mark4asp** [arekbal/GherkinSpec#9]
Using VS2017 Community. I fail to install GherkinSpec.NUnit to a project via NuGet using the Package Manager Console. I am trying to install it to a project here: '\apogalenos\UnitTests\UnitTests' called UnitTests within a UnitTests folder.  My solution folder is at '\apogalenos\ApoG Desktop'

=========================================================
PM> Install-Package GherkinSpec.NUnit -Version 3.0.2
=========================================================
Attempting to gather dependency information for package 'GherkinSpec.NUnit.3.0.2' with respect to project 'Applications\ApoG Desktop', targeting '.NETFramework,Version=v4.6'
Gathering dependency information took 11.62 ms
Attempting to resolve dependencies for package 'GherkinSpec.NUnit.3.0.2' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'GherkinSpec.NUnit.3.0.2'
Resolved actions to install package 'GherkinSpec.NUnit.3.0.2'
Retrieving package 'GherkinSpec.NUnit 3.0.2' from 'nuget.org'.
Install failed. Rolling back...
Package 'GherkinSpec.NUnit.3.0.2' does not exist in project 'ApoG Desktop'
Package 'GherkinSpec.NUnit.3.0.2' does not exist in folder 'D:\APOG\_trunk_new\apogalenos\ApoG Desktop\packages'
Executing nuget actions took 1.68 sec
Install-Package : Could not install package 'GherkinSpec.NUnit 3.0.2'. You are trying to install this package into a project that targets 
'.NETFramework,Version=v4.6', but the package does not contain any assembly references or content files that are compatible with that framework. For 
more information, contact the package author.
At line:1 char:1
+ Install-Package GherkinSpec.NUnit -Version 3.0.2
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Time Elapsed: 00:00:01.8802732

**Comment by arekbal** [comment]
Hello.
Thanks for writing down your issue.

With version 3.0 I added support for .Net Standard 2.0 which is now a baseline for library developers to support .net core, and .net framework with same code. I went with latest 2.0 version which requires 4.6.1 framework version at the minimum. I haven't tested this, but I assume 2.0 would not be compatible with 1.* versions.

[msdn net standard](https://docs.microsoft.com/en-us/dotnet/standard/net-standard)
I am sorry for inconvenience. 

EDIT: I found the following recommendation behind the link I gave earlier:

> In general, we recommend you to target the lowest version of .NET Standard possible. So, after you find the highest .NET Standard version you can target, follow these steps:
> 
>     Target the next lower version of .NET Standard and build your project.
>     If your project builds successfully, repeat step 1. Otherwise, retarget to the next higher version and that's the version you should use.

So, I guess after investigating it a bit further I might go with it and see how low I can get (I don't use some specific APIs so I believe I could go as low as NetStandard1.0).

EDIT2: Actually the lowest I could get to is 1.5 because that is the lowest Gherkin package itself goes.
EDIT3: Tried to go with 1.5 but it still lacks basic APIs such as Environment.CurrentDirectory. No wonder they got pressured and rushed to 2.0. Moving to 2.0 was simple. Lowering the version would be a bit of pain. Currently not worth it. :)
